// Generated by gencpp from file exploration_msgs/Branch.msg
// DO NOT EDIT!


#ifndef EXPLORATION_MSGS_MESSAGE_BRANCH_H
#define EXPLORATION_MSGS_MESSAGE_BRANCH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace exploration_msgs
{
template <class ContainerAllocator>
struct Branch_
{
  typedef Branch_<ContainerAllocator> Type;

  Branch_()
    : point()
    , status(0)  {
    }
  Branch_(const ContainerAllocator& _alloc)
    : point(_alloc)
    , status(0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _point_type;
  _point_type point;

   typedef uint8_t _status_type;
  _status_type status;



  enum {
    NORMAL = 0u,
    OLDER_DUPLICATION = 1u,
    NEWER_DUPLICATION = 2u,
    ON_MAP = 3u,
  };


  typedef boost::shared_ptr< ::exploration_msgs::Branch_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exploration_msgs::Branch_<ContainerAllocator> const> ConstPtr;

}; // struct Branch_

typedef ::exploration_msgs::Branch_<std::allocator<void> > Branch;

typedef boost::shared_ptr< ::exploration_msgs::Branch > BranchPtr;
typedef boost::shared_ptr< ::exploration_msgs::Branch const> BranchConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exploration_msgs::Branch_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exploration_msgs::Branch_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace exploration_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'exploration_msgs': ['/home/ros/catkin_ws/src/multiple_robots_slam/exploration_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::exploration_msgs::Branch_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exploration_msgs::Branch_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exploration_msgs::Branch_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exploration_msgs::Branch_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exploration_msgs::Branch_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exploration_msgs::Branch_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exploration_msgs::Branch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ac2bb0e3b3b461e0f1c8e34dca5c8ba9";
  }

  static const char* value(const ::exploration_msgs::Branch_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xac2bb0e3b3b461e0ULL;
  static const uint64_t static_value2 = 0xf1c8e34dca5c8ba9ULL;
};

template<class ContainerAllocator>
struct DataType< ::exploration_msgs::Branch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exploration_msgs/Branch";
  }

  static const char* value(const ::exploration_msgs::Branch_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exploration_msgs::Branch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 NORMAL = 0\n\
uint8 OLDER_DUPLICATION = 1\n\
uint8 NEWER_DUPLICATION = 2\n\
uint8 ON_MAP = 3\n\
\n\
geometry_msgs/Point point\n\
uint8 status\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::exploration_msgs::Branch_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exploration_msgs::Branch_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.point);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Branch_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exploration_msgs::Branch_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exploration_msgs::Branch_<ContainerAllocator>& v)
  {
    s << indent << "point: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.point);
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXPLORATION_MSGS_MESSAGE_BRANCH_H
