// Generated by gencpp from file exploration_msgs/RobotInfoArray.msg
// DO NOT EDIT!


#ifndef EXPLORATION_MSGS_MESSAGE_ROBOTINFOARRAY_H
#define EXPLORATION_MSGS_MESSAGE_ROBOTINFOARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <exploration_msgs/RobotInfo.h>

namespace exploration_msgs
{
template <class ContainerAllocator>
struct RobotInfoArray_
{
  typedef RobotInfoArray_<ContainerAllocator> Type;

  RobotInfoArray_()
    : header()
    , info()  {
    }
  RobotInfoArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , info(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::exploration_msgs::RobotInfo_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::exploration_msgs::RobotInfo_<ContainerAllocator> >::other >  _info_type;
  _info_type info;





  typedef boost::shared_ptr< ::exploration_msgs::RobotInfoArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exploration_msgs::RobotInfoArray_<ContainerAllocator> const> ConstPtr;

}; // struct RobotInfoArray_

typedef ::exploration_msgs::RobotInfoArray_<std::allocator<void> > RobotInfoArray;

typedef boost::shared_ptr< ::exploration_msgs::RobotInfoArray > RobotInfoArrayPtr;
typedef boost::shared_ptr< ::exploration_msgs::RobotInfoArray const> RobotInfoArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exploration_msgs::RobotInfoArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exploration_msgs::RobotInfoArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace exploration_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'exploration_msgs': ['/home/ros/catkin_ws/src/multiple_robots_slam/exploration_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::exploration_msgs::RobotInfoArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exploration_msgs::RobotInfoArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exploration_msgs::RobotInfoArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exploration_msgs::RobotInfoArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exploration_msgs::RobotInfoArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exploration_msgs::RobotInfoArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exploration_msgs::RobotInfoArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dcb6a4c494c1e1b789d0136f804a0c6f";
  }

  static const char* value(const ::exploration_msgs::RobotInfoArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdcb6a4c494c1e1b7ULL;
  static const uint64_t static_value2 = 0x89d0136f804a0c6fULL;
};

template<class ContainerAllocator>
struct DataType< ::exploration_msgs::RobotInfoArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exploration_msgs/RobotInfoArray";
  }

  static const char* value(const ::exploration_msgs::RobotInfoArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exploration_msgs::RobotInfoArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
exploration_msgs/RobotInfo[] info\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: exploration_msgs/RobotInfo\n\
string name\n\
geometry_msgs/Pose pose\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::exploration_msgs::RobotInfoArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exploration_msgs::RobotInfoArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotInfoArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exploration_msgs::RobotInfoArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exploration_msgs::RobotInfoArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "info[]" << std::endl;
    for (size_t i = 0; i < v.info.size(); ++i)
    {
      s << indent << "  info[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::exploration_msgs::RobotInfo_<ContainerAllocator> >::stream(s, indent + "    ", v.info[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXPLORATION_MSGS_MESSAGE_ROBOTINFOARRAY_H
