//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the exploration package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __exploration__MOVEMENT_PARAMETER_RECONFIGURECONFIG_H__
#define __exploration__MOVEMENT_PARAMETER_RECONFIGURECONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace exploration
{
  class movement_parameter_reconfigureConfigStatics;

  class movement_parameter_reconfigureConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(movement_parameter_reconfigureConfig &config, const movement_parameter_reconfigureConfig &max, const movement_parameter_reconfigureConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const movement_parameter_reconfigureConfig &config1, const movement_parameter_reconfigureConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, movement_parameter_reconfigureConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const movement_parameter_reconfigureConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, movement_parameter_reconfigureConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const movement_parameter_reconfigureConfig &config) const = 0;
      virtual void getValue(const movement_parameter_reconfigureConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T movement_parameter_reconfigureConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (movement_parameter_reconfigureConfig::* field);

      virtual void clamp(movement_parameter_reconfigureConfig &config, const movement_parameter_reconfigureConfig &max, const movement_parameter_reconfigureConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const movement_parameter_reconfigureConfig &config1, const movement_parameter_reconfigureConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, movement_parameter_reconfigureConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const movement_parameter_reconfigureConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, movement_parameter_reconfigureConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const movement_parameter_reconfigureConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const movement_parameter_reconfigureConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, movement_parameter_reconfigureConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, movement_parameter_reconfigureConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<movement_parameter_reconfigureConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(movement_parameter_reconfigureConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("forward_velocity"==(*_i)->name){forward_velocity = boost::any_cast<double>(val);}
        if("rotation_velocity"==(*_i)->name){rotation_velocity = boost::any_cast<double>(val);}
        if("curve_gain"==(*_i)->name){curve_gain = boost::any_cast<double>(val);}
        if("use_angle_bias"==(*_i)->name){use_angle_bias = boost::any_cast<bool>(val);}
        if("angle_bias"==(*_i)->name){angle_bias = boost::any_cast<double>(val);}
        if("costmap_margin"==(*_i)->name){costmap_margin = boost::any_cast<double>(val);}
        if("esc_map_div_x"==(*_i)->name){esc_map_div_x = boost::any_cast<int>(val);}
        if("esc_map_div_y"==(*_i)->name){esc_map_div_y = boost::any_cast<int>(val);}
        if("esc_map_width"==(*_i)->name){esc_map_width = boost::any_cast<double>(val);}
        if("esc_map_height"==(*_i)->name){esc_map_height = boost::any_cast<double>(val);}
        if("rotation_tolerance"==(*_i)->name){rotation_tolerance = boost::any_cast<double>(val);}
        if("goal_reset_rate"==(*_i)->name){goal_reset_rate = boost::any_cast<double>(val);}
        if("path_back_interval"==(*_i)->name){path_back_interval = boost::any_cast<int>(val);}
        if("reset_goal_path_limit"==(*_i)->name){reset_goal_path_limit = boost::any_cast<int>(val);}
        if("reset_goal_path_rate"==(*_i)->name){reset_goal_path_rate = boost::any_cast<double>(val);}
        if("back_velocity"==(*_i)->name){back_velocity = boost::any_cast<double>(val);}
        if("back_time"==(*_i)->name){back_time = boost::any_cast<double>(val);}
        if("road_center_threshold"==(*_i)->name){road_center_threshold = boost::any_cast<double>(val);}
        if("road_threshold"==(*_i)->name){road_threshold = boost::any_cast<double>(val);}
        if("road_center_gain"==(*_i)->name){road_center_gain = boost::any_cast<double>(val);}
        if("forward_angle"==(*_i)->name){forward_angle = boost::any_cast<double>(val);}
        if("vfh_far_range_threshold"==(*_i)->name){vfh_far_range_threshold = boost::any_cast<double>(val);}
        if("vfh_near_range_threshold"==(*_i)->name){vfh_near_range_threshold = boost::any_cast<double>(val);}
        if("vfh_rate_threshold"==(*_i)->name){vfh_rate_threshold = boost::any_cast<double>(val);}
        if("far_avoidance_gain"==(*_i)->name){far_avoidance_gain = boost::any_cast<double>(val);}
        if("near_avoidance_gain"==(*_i)->name){near_avoidance_gain = boost::any_cast<double>(val);}
        if("calc_range_cos"==(*_i)->name){calc_range_cos = boost::any_cast<bool>(val);}
        if("emergency_threshold"==(*_i)->name){emergency_threshold = boost::any_cast<double>(val);}
        if("emergency_diff_threshold"==(*_i)->name){emergency_diff_threshold = boost::any_cast<double>(val);}
        if("emergency_avoidance_gain"==(*_i)->name){emergency_avoidance_gain = boost::any_cast<double>(val);}
        if("approach_wall"==(*_i)->name){approach_wall = boost::any_cast<bool>(val);}
        if("wall_forward_angle"==(*_i)->name){wall_forward_angle = boost::any_cast<double>(val);}
        if("wall_rate_threshold"==(*_i)->name){wall_rate_threshold = boost::any_cast<double>(val);}
        if("wall_distance_upper_threshold"==(*_i)->name){wall_distance_upper_threshold = boost::any_cast<double>(val);}
        if("wall_distance_lower_threshold"==(*_i)->name){wall_distance_lower_threshold = boost::any_cast<double>(val);}
      }
    }

    double forward_velocity;
double rotation_velocity;
double curve_gain;
bool use_angle_bias;
double angle_bias;
double costmap_margin;
int esc_map_div_x;
int esc_map_div_y;
double esc_map_width;
double esc_map_height;
double rotation_tolerance;
double goal_reset_rate;
int path_back_interval;
int reset_goal_path_limit;
double reset_goal_path_rate;
double back_velocity;
double back_time;
double road_center_threshold;
double road_threshold;
double road_center_gain;
double forward_angle;
double vfh_far_range_threshold;
double vfh_near_range_threshold;
double vfh_rate_threshold;
double far_avoidance_gain;
double near_avoidance_gain;
bool calc_range_cos;
double emergency_threshold;
double emergency_diff_threshold;
double emergency_avoidance_gain;
bool approach_wall;
double wall_forward_angle;
double wall_rate_threshold;
double wall_distance_upper_threshold;
double wall_distance_lower_threshold;

    bool state;
    std::string name;

    
}groups;



//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double forward_velocity;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double rotation_velocity;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double curve_gain;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool use_angle_bias;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double angle_bias;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double costmap_margin;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int esc_map_div_x;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int esc_map_div_y;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double esc_map_width;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double esc_map_height;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double rotation_tolerance;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double goal_reset_rate;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int path_back_interval;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int reset_goal_path_limit;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double reset_goal_path_rate;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double back_velocity;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double back_time;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double road_center_threshold;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double road_threshold;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double road_center_gain;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double forward_angle;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vfh_far_range_threshold;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vfh_near_range_threshold;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vfh_rate_threshold;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double far_avoidance_gain;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double near_avoidance_gain;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool calc_range_cos;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double emergency_threshold;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double emergency_diff_threshold;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double emergency_avoidance_gain;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool approach_wall;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double wall_forward_angle;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double wall_rate_threshold;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double wall_distance_upper_threshold;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double wall_distance_lower_threshold;
//#line 228 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("movement_parameter_reconfigureConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const movement_parameter_reconfigureConfig &__max__ = __getMax__();
      const movement_parameter_reconfigureConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const movement_parameter_reconfigureConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const movement_parameter_reconfigureConfig &__getDefault__();
    static const movement_parameter_reconfigureConfig &__getMax__();
    static const movement_parameter_reconfigureConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const movement_parameter_reconfigureConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void movement_parameter_reconfigureConfig::ParamDescription<std::string>::clamp(movement_parameter_reconfigureConfig &config, const movement_parameter_reconfigureConfig &max, const movement_parameter_reconfigureConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class movement_parameter_reconfigureConfigStatics
  {
    friend class movement_parameter_reconfigureConfig;

    movement_parameter_reconfigureConfigStatics()
    {
movement_parameter_reconfigureConfig::GroupDescription<movement_parameter_reconfigureConfig::DEFAULT, movement_parameter_reconfigureConfig> Default("Default", "", 0, 0, true, &movement_parameter_reconfigureConfig::groups);
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.forward_velocity = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.forward_velocity = 2.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.forward_velocity = 0.2;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("forward_velocity", "double", 0, "", "", &movement_parameter_reconfigureConfig::forward_velocity)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("forward_velocity", "double", 0, "", "", &movement_parameter_reconfigureConfig::forward_velocity)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.rotation_velocity = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.rotation_velocity = 2.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.rotation_velocity = 0.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("rotation_velocity", "double", 0, "", "", &movement_parameter_reconfigureConfig::rotation_velocity)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("rotation_velocity", "double", 0, "", "", &movement_parameter_reconfigureConfig::rotation_velocity)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.curve_gain = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.curve_gain = 5.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.curve_gain = 2.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("curve_gain", "double", 0, "", "", &movement_parameter_reconfigureConfig::curve_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("curve_gain", "double", 0, "", "", &movement_parameter_reconfigureConfig::curve_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.use_angle_bias = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.use_angle_bias = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.use_angle_bias = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<bool>("use_angle_bias", "bool", 0, "", "", &movement_parameter_reconfigureConfig::use_angle_bias)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<bool>("use_angle_bias", "bool", 0, "", "", &movement_parameter_reconfigureConfig::use_angle_bias)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.angle_bias = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.angle_bias = 90.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.angle_bias = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("angle_bias", "double", 0, "", "", &movement_parameter_reconfigureConfig::angle_bias)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("angle_bias", "double", 0, "", "", &movement_parameter_reconfigureConfig::angle_bias)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.costmap_margin = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.costmap_margin = 5.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.costmap_margin = 0.4;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("costmap_margin", "double", 0, "", "", &movement_parameter_reconfigureConfig::costmap_margin)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("costmap_margin", "double", 0, "", "", &movement_parameter_reconfigureConfig::costmap_margin)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.esc_map_div_x = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.esc_map_div_x = 30;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.esc_map_div_x = 3;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<int>("esc_map_div_x", "int", 0, "", "", &movement_parameter_reconfigureConfig::esc_map_div_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<int>("esc_map_div_x", "int", 0, "", "", &movement_parameter_reconfigureConfig::esc_map_div_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.esc_map_div_y = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.esc_map_div_y = 30;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.esc_map_div_y = 3;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<int>("esc_map_div_y", "int", 0, "", "", &movement_parameter_reconfigureConfig::esc_map_div_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<int>("esc_map_div_y", "int", 0, "", "", &movement_parameter_reconfigureConfig::esc_map_div_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.esc_map_width = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.esc_map_width = 5.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.esc_map_width = 0.9;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("esc_map_width", "double", 0, "", "", &movement_parameter_reconfigureConfig::esc_map_width)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("esc_map_width", "double", 0, "", "", &movement_parameter_reconfigureConfig::esc_map_width)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.esc_map_height = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.esc_map_height = 5.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.esc_map_height = 0.9;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("esc_map_height", "double", 0, "", "", &movement_parameter_reconfigureConfig::esc_map_height)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("esc_map_height", "double", 0, "", "", &movement_parameter_reconfigureConfig::esc_map_height)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.rotation_tolerance = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.rotation_tolerance = 3.14;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.rotation_tolerance = 0.05;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("rotation_tolerance", "double", 0, "", "", &movement_parameter_reconfigureConfig::rotation_tolerance)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("rotation_tolerance", "double", 0, "", "", &movement_parameter_reconfigureConfig::rotation_tolerance)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.goal_reset_rate = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.goal_reset_rate = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.goal_reset_rate = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("goal_reset_rate", "double", 0, "", "", &movement_parameter_reconfigureConfig::goal_reset_rate)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("goal_reset_rate", "double", 0, "", "", &movement_parameter_reconfigureConfig::goal_reset_rate)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.path_back_interval = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.path_back_interval = 50;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.path_back_interval = 5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<int>("path_back_interval", "int", 0, "", "", &movement_parameter_reconfigureConfig::path_back_interval)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<int>("path_back_interval", "int", 0, "", "", &movement_parameter_reconfigureConfig::path_back_interval)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.reset_goal_path_limit = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.reset_goal_path_limit = 120;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.reset_goal_path_limit = 30;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<int>("reset_goal_path_limit", "int", 0, "", "", &movement_parameter_reconfigureConfig::reset_goal_path_limit)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<int>("reset_goal_path_limit", "int", 0, "", "", &movement_parameter_reconfigureConfig::reset_goal_path_limit)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.reset_goal_path_rate = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.reset_goal_path_rate = 30.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.reset_goal_path_rate = 0.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("reset_goal_path_rate", "double", 0, "", "", &movement_parameter_reconfigureConfig::reset_goal_path_rate)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("reset_goal_path_rate", "double", 0, "", "", &movement_parameter_reconfigureConfig::reset_goal_path_rate)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.back_velocity = -2.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.back_velocity = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.back_velocity = -0.2;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("back_velocity", "double", 0, "", "", &movement_parameter_reconfigureConfig::back_velocity)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("back_velocity", "double", 0, "", "", &movement_parameter_reconfigureConfig::back_velocity)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.back_time = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.back_time = 2.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.back_time = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("back_time", "double", 0, "", "", &movement_parameter_reconfigureConfig::back_time)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("back_time", "double", 0, "", "", &movement_parameter_reconfigureConfig::back_time)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.road_center_threshold = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.road_center_threshold = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.road_center_threshold = 5.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("road_center_threshold", "double", 0, "", "", &movement_parameter_reconfigureConfig::road_center_threshold)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("road_center_threshold", "double", 0, "", "", &movement_parameter_reconfigureConfig::road_center_threshold)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.road_threshold = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.road_threshold = 5.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.road_threshold = 1.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("road_threshold", "double", 0, "", "", &movement_parameter_reconfigureConfig::road_threshold)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("road_threshold", "double", 0, "", "", &movement_parameter_reconfigureConfig::road_threshold)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.road_center_gain = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.road_center_gain = 5.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.road_center_gain = 1.25;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("road_center_gain", "double", 0, "", "", &movement_parameter_reconfigureConfig::road_center_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("road_center_gain", "double", 0, "", "", &movement_parameter_reconfigureConfig::road_center_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.forward_angle = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.forward_angle = 0.7;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.forward_angle = 0.35;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("forward_angle", "double", 0, "", "", &movement_parameter_reconfigureConfig::forward_angle)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("forward_angle", "double", 0, "", "", &movement_parameter_reconfigureConfig::forward_angle)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vfh_far_range_threshold = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vfh_far_range_threshold = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vfh_far_range_threshold = 4.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("vfh_far_range_threshold", "double", 0, "", "", &movement_parameter_reconfigureConfig::vfh_far_range_threshold)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("vfh_far_range_threshold", "double", 0, "", "", &movement_parameter_reconfigureConfig::vfh_far_range_threshold)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vfh_near_range_threshold = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vfh_near_range_threshold = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vfh_near_range_threshold = 1.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("vfh_near_range_threshold", "double", 0, "", "", &movement_parameter_reconfigureConfig::vfh_near_range_threshold)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("vfh_near_range_threshold", "double", 0, "", "", &movement_parameter_reconfigureConfig::vfh_near_range_threshold)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vfh_rate_threshold = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vfh_rate_threshold = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vfh_rate_threshold = 0.9;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("vfh_rate_threshold", "double", 0, "", "", &movement_parameter_reconfigureConfig::vfh_rate_threshold)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("vfh_rate_threshold", "double", 0, "", "", &movement_parameter_reconfigureConfig::vfh_rate_threshold)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.far_avoidance_gain = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.far_avoidance_gain = 5.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.far_avoidance_gain = 2.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("far_avoidance_gain", "double", 0, "", "", &movement_parameter_reconfigureConfig::far_avoidance_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("far_avoidance_gain", "double", 0, "", "", &movement_parameter_reconfigureConfig::far_avoidance_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.near_avoidance_gain = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.near_avoidance_gain = 5.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.near_avoidance_gain = 2.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("near_avoidance_gain", "double", 0, "", "", &movement_parameter_reconfigureConfig::near_avoidance_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("near_avoidance_gain", "double", 0, "", "", &movement_parameter_reconfigureConfig::near_avoidance_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.calc_range_cos = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.calc_range_cos = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.calc_range_cos = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<bool>("calc_range_cos", "bool", 0, "", "", &movement_parameter_reconfigureConfig::calc_range_cos)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<bool>("calc_range_cos", "bool", 0, "", "", &movement_parameter_reconfigureConfig::calc_range_cos)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.emergency_threshold = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.emergency_threshold = 2.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.emergency_threshold = 0.1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("emergency_threshold", "double", 0, "", "", &movement_parameter_reconfigureConfig::emergency_threshold)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("emergency_threshold", "double", 0, "", "", &movement_parameter_reconfigureConfig::emergency_threshold)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.emergency_diff_threshold = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.emergency_diff_threshold = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.emergency_diff_threshold = 0.1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("emergency_diff_threshold", "double", 0, "", "", &movement_parameter_reconfigureConfig::emergency_diff_threshold)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("emergency_diff_threshold", "double", 0, "", "", &movement_parameter_reconfigureConfig::emergency_diff_threshold)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.emergency_avoidance_gain = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.emergency_avoidance_gain = 5.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.emergency_avoidance_gain = 3.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("emergency_avoidance_gain", "double", 0, "", "", &movement_parameter_reconfigureConfig::emergency_avoidance_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("emergency_avoidance_gain", "double", 0, "", "", &movement_parameter_reconfigureConfig::emergency_avoidance_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.approach_wall = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.approach_wall = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.approach_wall = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<bool>("approach_wall", "bool", 0, "", "", &movement_parameter_reconfigureConfig::approach_wall)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<bool>("approach_wall", "bool", 0, "", "", &movement_parameter_reconfigureConfig::approach_wall)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.wall_forward_angle = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.wall_forward_angle = 0.7;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.wall_forward_angle = 0.35;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("wall_forward_angle", "double", 0, "", "", &movement_parameter_reconfigureConfig::wall_forward_angle)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("wall_forward_angle", "double", 0, "", "", &movement_parameter_reconfigureConfig::wall_forward_angle)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.wall_rate_threshold = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.wall_rate_threshold = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.wall_rate_threshold = 0.8;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("wall_rate_threshold", "double", 0, "", "", &movement_parameter_reconfigureConfig::wall_rate_threshold)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("wall_rate_threshold", "double", 0, "", "", &movement_parameter_reconfigureConfig::wall_rate_threshold)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.wall_distance_upper_threshold = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.wall_distance_upper_threshold = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.wall_distance_upper_threshold = 5.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("wall_distance_upper_threshold", "double", 0, "", "", &movement_parameter_reconfigureConfig::wall_distance_upper_threshold)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("wall_distance_upper_threshold", "double", 0, "", "", &movement_parameter_reconfigureConfig::wall_distance_upper_threshold)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.wall_distance_lower_threshold = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.wall_distance_lower_threshold = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.wall_distance_lower_threshold = 0.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("wall_distance_lower_threshold", "double", 0, "", "", &movement_parameter_reconfigureConfig::wall_distance_lower_threshold)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new movement_parameter_reconfigureConfig::ParamDescription<double>("wall_distance_lower_threshold", "double", 0, "", "", &movement_parameter_reconfigureConfig::wall_distance_lower_threshold)));
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(movement_parameter_reconfigureConfig::AbstractGroupDescriptionConstPtr(new movement_parameter_reconfigureConfig::GroupDescription<movement_parameter_reconfigureConfig::DEFAULT, movement_parameter_reconfigureConfig>(Default)));
//#line 366 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<movement_parameter_reconfigureConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<movement_parameter_reconfigureConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    movement_parameter_reconfigureConfig __max__;
    movement_parameter_reconfigureConfig __min__;
    movement_parameter_reconfigureConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const movement_parameter_reconfigureConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static movement_parameter_reconfigureConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &movement_parameter_reconfigureConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const movement_parameter_reconfigureConfig &movement_parameter_reconfigureConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const movement_parameter_reconfigureConfig &movement_parameter_reconfigureConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const movement_parameter_reconfigureConfig &movement_parameter_reconfigureConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<movement_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr> &movement_parameter_reconfigureConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<movement_parameter_reconfigureConfig::AbstractGroupDescriptionConstPtr> &movement_parameter_reconfigureConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const movement_parameter_reconfigureConfigStatics *movement_parameter_reconfigureConfig::__get_statics__()
  {
    const static movement_parameter_reconfigureConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = movement_parameter_reconfigureConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __MOVEMENT_PARAMETER_RECONFIGURERECONFIGURATOR_H__
