//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the exploration package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __exploration__MULTI_EXPLORATION_SIMULATORCONFIG_H__
#define __exploration__MULTI_EXPLORATION_SIMULATORCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace exploration
{
  class multi_exploration_simulatorConfigStatics;

  class multi_exploration_simulatorConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(multi_exploration_simulatorConfig &config, const multi_exploration_simulatorConfig &max, const multi_exploration_simulatorConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const multi_exploration_simulatorConfig &config1, const multi_exploration_simulatorConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, multi_exploration_simulatorConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const multi_exploration_simulatorConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, multi_exploration_simulatorConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const multi_exploration_simulatorConfig &config) const = 0;
      virtual void getValue(const multi_exploration_simulatorConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T multi_exploration_simulatorConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (multi_exploration_simulatorConfig::* field);

      virtual void clamp(multi_exploration_simulatorConfig &config, const multi_exploration_simulatorConfig &max, const multi_exploration_simulatorConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const multi_exploration_simulatorConfig &config1, const multi_exploration_simulatorConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, multi_exploration_simulatorConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const multi_exploration_simulatorConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, multi_exploration_simulatorConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const multi_exploration_simulatorConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const multi_exploration_simulatorConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, multi_exploration_simulatorConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, multi_exploration_simulatorConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<multi_exploration_simulatorConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(multi_exploration_simulatorConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("simulate_robot_index"==(*_i)->name){simulate_robot_index = boost::any_cast<int>(val);}
        if("robot_number"==(*_i)->name){robot_number = boost::any_cast<int>(val);}
        if("branch_number"==(*_i)->name){branch_number = boost::any_cast<int>(val);}
        if("frontier_number"==(*_i)->name){frontier_number = boost::any_cast<int>(val);}
        if("robot1_x"==(*_i)->name){robot1_x = boost::any_cast<double>(val);}
        if("robot1_y"==(*_i)->name){robot1_y = boost::any_cast<double>(val);}
        if("robot1_yaw"==(*_i)->name){robot1_yaw = boost::any_cast<double>(val);}
        if("robot2_x"==(*_i)->name){robot2_x = boost::any_cast<double>(val);}
        if("robot2_y"==(*_i)->name){robot2_y = boost::any_cast<double>(val);}
        if("robot2_yaw"==(*_i)->name){robot2_yaw = boost::any_cast<double>(val);}
        if("robot3_x"==(*_i)->name){robot3_x = boost::any_cast<double>(val);}
        if("robot3_y"==(*_i)->name){robot3_y = boost::any_cast<double>(val);}
        if("robot3_yaw"==(*_i)->name){robot3_yaw = boost::any_cast<double>(val);}
        if("robot4_x"==(*_i)->name){robot4_x = boost::any_cast<double>(val);}
        if("robot4_y"==(*_i)->name){robot4_y = boost::any_cast<double>(val);}
        if("robot4_yaw"==(*_i)->name){robot4_yaw = boost::any_cast<double>(val);}
        if("robot5_x"==(*_i)->name){robot5_x = boost::any_cast<double>(val);}
        if("robot5_y"==(*_i)->name){robot5_y = boost::any_cast<double>(val);}
        if("robot5_yaw"==(*_i)->name){robot5_yaw = boost::any_cast<double>(val);}
        if("branch1_x"==(*_i)->name){branch1_x = boost::any_cast<double>(val);}
        if("branch1_y"==(*_i)->name){branch1_y = boost::any_cast<double>(val);}
        if("branch2_x"==(*_i)->name){branch2_x = boost::any_cast<double>(val);}
        if("branch2_y"==(*_i)->name){branch2_y = boost::any_cast<double>(val);}
        if("branch3_x"==(*_i)->name){branch3_x = boost::any_cast<double>(val);}
        if("branch3_y"==(*_i)->name){branch3_y = boost::any_cast<double>(val);}
        if("branch4_x"==(*_i)->name){branch4_x = boost::any_cast<double>(val);}
        if("branch4_y"==(*_i)->name){branch4_y = boost::any_cast<double>(val);}
        if("branch5_x"==(*_i)->name){branch5_x = boost::any_cast<double>(val);}
        if("branch5_y"==(*_i)->name){branch5_y = boost::any_cast<double>(val);}
        if("frontier1_x"==(*_i)->name){frontier1_x = boost::any_cast<double>(val);}
        if("frontier1_y"==(*_i)->name){frontier1_y = boost::any_cast<double>(val);}
        if("frontier2_x"==(*_i)->name){frontier2_x = boost::any_cast<double>(val);}
        if("frontier2_y"==(*_i)->name){frontier2_y = boost::any_cast<double>(val);}
        if("frontier3_x"==(*_i)->name){frontier3_x = boost::any_cast<double>(val);}
        if("frontier3_y"==(*_i)->name){frontier3_y = boost::any_cast<double>(val);}
        if("frontier4_x"==(*_i)->name){frontier4_x = boost::any_cast<double>(val);}
        if("frontier4_y"==(*_i)->name){frontier4_y = boost::any_cast<double>(val);}
        if("frontier5_x"==(*_i)->name){frontier5_x = boost::any_cast<double>(val);}
        if("frontier5_y"==(*_i)->name){frontier5_y = boost::any_cast<double>(val);}
        if("frontier6_x"==(*_i)->name){frontier6_x = boost::any_cast<double>(val);}
        if("frontier6_y"==(*_i)->name){frontier6_y = boost::any_cast<double>(val);}
        if("frontier7_x"==(*_i)->name){frontier7_x = boost::any_cast<double>(val);}
        if("frontier7_y"==(*_i)->name){frontier7_y = boost::any_cast<double>(val);}
        if("frontier8_x"==(*_i)->name){frontier8_x = boost::any_cast<double>(val);}
        if("frontier8_y"==(*_i)->name){frontier8_y = boost::any_cast<double>(val);}
        if("frontier9_x"==(*_i)->name){frontier9_x = boost::any_cast<double>(val);}
        if("frontier9_y"==(*_i)->name){frontier9_y = boost::any_cast<double>(val);}
        if("frontier10_x"==(*_i)->name){frontier10_x = boost::any_cast<double>(val);}
        if("frontier10_y"==(*_i)->name){frontier10_y = boost::any_cast<double>(val);}
      }
    }

    int simulate_robot_index;
int robot_number;
int branch_number;
int frontier_number;
double robot1_x;
double robot1_y;
double robot1_yaw;
double robot2_x;
double robot2_y;
double robot2_yaw;
double robot3_x;
double robot3_y;
double robot3_yaw;
double robot4_x;
double robot4_y;
double robot4_yaw;
double robot5_x;
double robot5_y;
double robot5_yaw;
double branch1_x;
double branch1_y;
double branch2_x;
double branch2_y;
double branch3_x;
double branch3_y;
double branch4_x;
double branch4_y;
double branch5_x;
double branch5_y;
double frontier1_x;
double frontier1_y;
double frontier2_x;
double frontier2_y;
double frontier3_x;
double frontier3_y;
double frontier4_x;
double frontier4_y;
double frontier5_x;
double frontier5_y;
double frontier6_x;
double frontier6_y;
double frontier7_x;
double frontier7_y;
double frontier8_x;
double frontier8_y;
double frontier9_x;
double frontier9_y;
double frontier10_x;
double frontier10_y;

    bool state;
    std::string name;

    
}groups;



//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int simulate_robot_index;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int robot_number;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int branch_number;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int frontier_number;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double robot1_x;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double robot1_y;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double robot1_yaw;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double robot2_x;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double robot2_y;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double robot2_yaw;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double robot3_x;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double robot3_y;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double robot3_yaw;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double robot4_x;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double robot4_y;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double robot4_yaw;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double robot5_x;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double robot5_y;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double robot5_yaw;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double branch1_x;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double branch1_y;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double branch2_x;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double branch2_y;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double branch3_x;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double branch3_y;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double branch4_x;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double branch4_y;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double branch5_x;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double branch5_y;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double frontier1_x;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double frontier1_y;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double frontier2_x;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double frontier2_y;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double frontier3_x;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double frontier3_y;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double frontier4_x;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double frontier4_y;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double frontier5_x;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double frontier5_y;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double frontier6_x;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double frontier6_y;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double frontier7_x;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double frontier7_y;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double frontier8_x;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double frontier8_y;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double frontier9_x;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double frontier9_y;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double frontier10_x;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double frontier10_y;
//#line 228 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("multi_exploration_simulatorConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const multi_exploration_simulatorConfig &__max__ = __getMax__();
      const multi_exploration_simulatorConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const multi_exploration_simulatorConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const multi_exploration_simulatorConfig &__getDefault__();
    static const multi_exploration_simulatorConfig &__getMax__();
    static const multi_exploration_simulatorConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const multi_exploration_simulatorConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void multi_exploration_simulatorConfig::ParamDescription<std::string>::clamp(multi_exploration_simulatorConfig &config, const multi_exploration_simulatorConfig &max, const multi_exploration_simulatorConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class multi_exploration_simulatorConfigStatics
  {
    friend class multi_exploration_simulatorConfig;

    multi_exploration_simulatorConfigStatics()
    {
multi_exploration_simulatorConfig::GroupDescription<multi_exploration_simulatorConfig::DEFAULT, multi_exploration_simulatorConfig> Default("Default", "", 0, 0, true, &multi_exploration_simulatorConfig::groups);
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.simulate_robot_index = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.simulate_robot_index = 5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.simulate_robot_index = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<int>("simulate_robot_index", "int", 0, "simulate robot index", "", &multi_exploration_simulatorConfig::simulate_robot_index)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<int>("simulate_robot_index", "int", 0, "simulate robot index", "", &multi_exploration_simulatorConfig::simulate_robot_index)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.robot_number = 2;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.robot_number = 5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.robot_number = 2;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<int>("robot_number", "int", 0, "number of robot", "", &multi_exploration_simulatorConfig::robot_number)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<int>("robot_number", "int", 0, "number of robot", "", &multi_exploration_simulatorConfig::robot_number)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.branch_number = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.branch_number = 5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.branch_number = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<int>("branch_number", "int", 0, "number of branch", "", &multi_exploration_simulatorConfig::branch_number)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<int>("branch_number", "int", 0, "number of branch", "", &multi_exploration_simulatorConfig::branch_number)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.frontier_number = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.frontier_number = 10;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.frontier_number = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<int>("frontier_number", "int", 0, "number of frontier", "", &multi_exploration_simulatorConfig::frontier_number)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<int>("frontier_number", "int", 0, "number of frontier", "", &multi_exploration_simulatorConfig::frontier_number)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.robot1_x = -3.7;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.robot1_x = 43.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.robot1_x = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("robot1_x", "double", 0, "coordinate-x of robot i", "", &multi_exploration_simulatorConfig::robot1_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("robot1_x", "double", 0, "coordinate-x of robot i", "", &multi_exploration_simulatorConfig::robot1_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.robot1_y = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.robot1_y = 13.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.robot1_y = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("robot1_y", "double", 0, "coordinate-y of robot i", "", &multi_exploration_simulatorConfig::robot1_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("robot1_y", "double", 0, "coordinate-y of robot i", "", &multi_exploration_simulatorConfig::robot1_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.robot1_yaw = -180.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.robot1_yaw = 180.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.robot1_yaw = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("robot1_yaw", "double", 0, "coordinate-yaw of robot i", "", &multi_exploration_simulatorConfig::robot1_yaw)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("robot1_yaw", "double", 0, "coordinate-yaw of robot i", "", &multi_exploration_simulatorConfig::robot1_yaw)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.robot2_x = -3.7;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.robot2_x = 43.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.robot2_x = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("robot2_x", "double", 0, "coordinate-x of robot i", "", &multi_exploration_simulatorConfig::robot2_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("robot2_x", "double", 0, "coordinate-x of robot i", "", &multi_exploration_simulatorConfig::robot2_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.robot2_y = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.robot2_y = 13.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.robot2_y = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("robot2_y", "double", 0, "coordinate-y of robot i", "", &multi_exploration_simulatorConfig::robot2_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("robot2_y", "double", 0, "coordinate-y of robot i", "", &multi_exploration_simulatorConfig::robot2_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.robot2_yaw = -180.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.robot2_yaw = 180.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.robot2_yaw = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("robot2_yaw", "double", 0, "coordinate-yaw of robot i", "", &multi_exploration_simulatorConfig::robot2_yaw)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("robot2_yaw", "double", 0, "coordinate-yaw of robot i", "", &multi_exploration_simulatorConfig::robot2_yaw)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.robot3_x = -3.7;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.robot3_x = 43.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.robot3_x = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("robot3_x", "double", 0, "coordinate-x of robot i", "", &multi_exploration_simulatorConfig::robot3_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("robot3_x", "double", 0, "coordinate-x of robot i", "", &multi_exploration_simulatorConfig::robot3_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.robot3_y = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.robot3_y = 13.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.robot3_y = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("robot3_y", "double", 0, "coordinate-y of robot i", "", &multi_exploration_simulatorConfig::robot3_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("robot3_y", "double", 0, "coordinate-y of robot i", "", &multi_exploration_simulatorConfig::robot3_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.robot3_yaw = -180.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.robot3_yaw = 180.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.robot3_yaw = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("robot3_yaw", "double", 0, "coordinate-yaw of robot i", "", &multi_exploration_simulatorConfig::robot3_yaw)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("robot3_yaw", "double", 0, "coordinate-yaw of robot i", "", &multi_exploration_simulatorConfig::robot3_yaw)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.robot4_x = -3.7;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.robot4_x = 43.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.robot4_x = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("robot4_x", "double", 0, "coordinate-x of robot i", "", &multi_exploration_simulatorConfig::robot4_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("robot4_x", "double", 0, "coordinate-x of robot i", "", &multi_exploration_simulatorConfig::robot4_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.robot4_y = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.robot4_y = 13.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.robot4_y = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("robot4_y", "double", 0, "coordinate-y of robot i", "", &multi_exploration_simulatorConfig::robot4_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("robot4_y", "double", 0, "coordinate-y of robot i", "", &multi_exploration_simulatorConfig::robot4_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.robot4_yaw = -180.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.robot4_yaw = 180.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.robot4_yaw = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("robot4_yaw", "double", 0, "coordinate-yaw of robot i", "", &multi_exploration_simulatorConfig::robot4_yaw)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("robot4_yaw", "double", 0, "coordinate-yaw of robot i", "", &multi_exploration_simulatorConfig::robot4_yaw)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.robot5_x = -3.7;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.robot5_x = 43.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.robot5_x = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("robot5_x", "double", 0, "coordinate-x of robot i", "", &multi_exploration_simulatorConfig::robot5_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("robot5_x", "double", 0, "coordinate-x of robot i", "", &multi_exploration_simulatorConfig::robot5_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.robot5_y = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.robot5_y = 13.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.robot5_y = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("robot5_y", "double", 0, "coordinate-y of robot i", "", &multi_exploration_simulatorConfig::robot5_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("robot5_y", "double", 0, "coordinate-y of robot i", "", &multi_exploration_simulatorConfig::robot5_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.robot5_yaw = -180.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.robot5_yaw = 180.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.robot5_yaw = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("robot5_yaw", "double", 0, "coordinate-yaw of robot i", "", &multi_exploration_simulatorConfig::robot5_yaw)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("robot5_yaw", "double", 0, "coordinate-yaw of robot i", "", &multi_exploration_simulatorConfig::robot5_yaw)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.branch1_x = -3.7;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.branch1_x = 43.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.branch1_x = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("branch1_x", "double", 0, "coordinate-x of branch i", "", &multi_exploration_simulatorConfig::branch1_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("branch1_x", "double", 0, "coordinate-x of branch i", "", &multi_exploration_simulatorConfig::branch1_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.branch1_y = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.branch1_y = 13.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.branch1_y = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("branch1_y", "double", 0, "coordinate-y of branch i", "", &multi_exploration_simulatorConfig::branch1_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("branch1_y", "double", 0, "coordinate-y of branch i", "", &multi_exploration_simulatorConfig::branch1_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.branch2_x = -3.7;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.branch2_x = 43.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.branch2_x = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("branch2_x", "double", 0, "coordinate-x of branch i", "", &multi_exploration_simulatorConfig::branch2_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("branch2_x", "double", 0, "coordinate-x of branch i", "", &multi_exploration_simulatorConfig::branch2_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.branch2_y = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.branch2_y = 13.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.branch2_y = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("branch2_y", "double", 0, "coordinate-y of branch i", "", &multi_exploration_simulatorConfig::branch2_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("branch2_y", "double", 0, "coordinate-y of branch i", "", &multi_exploration_simulatorConfig::branch2_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.branch3_x = -3.7;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.branch3_x = 43.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.branch3_x = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("branch3_x", "double", 0, "coordinate-x of branch i", "", &multi_exploration_simulatorConfig::branch3_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("branch3_x", "double", 0, "coordinate-x of branch i", "", &multi_exploration_simulatorConfig::branch3_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.branch3_y = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.branch3_y = 13.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.branch3_y = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("branch3_y", "double", 0, "coordinate-y of branch i", "", &multi_exploration_simulatorConfig::branch3_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("branch3_y", "double", 0, "coordinate-y of branch i", "", &multi_exploration_simulatorConfig::branch3_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.branch4_x = -3.7;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.branch4_x = 43.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.branch4_x = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("branch4_x", "double", 0, "coordinate-x of branch i", "", &multi_exploration_simulatorConfig::branch4_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("branch4_x", "double", 0, "coordinate-x of branch i", "", &multi_exploration_simulatorConfig::branch4_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.branch4_y = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.branch4_y = 13.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.branch4_y = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("branch4_y", "double", 0, "coordinate-y of branch i", "", &multi_exploration_simulatorConfig::branch4_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("branch4_y", "double", 0, "coordinate-y of branch i", "", &multi_exploration_simulatorConfig::branch4_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.branch5_x = -3.7;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.branch5_x = 43.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.branch5_x = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("branch5_x", "double", 0, "coordinate-x of branch i", "", &multi_exploration_simulatorConfig::branch5_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("branch5_x", "double", 0, "coordinate-x of branch i", "", &multi_exploration_simulatorConfig::branch5_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.branch5_y = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.branch5_y = 13.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.branch5_y = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("branch5_y", "double", 0, "coordinate-y of branch i", "", &multi_exploration_simulatorConfig::branch5_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("branch5_y", "double", 0, "coordinate-y of branch i", "", &multi_exploration_simulatorConfig::branch5_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.frontier1_x = -3.7;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.frontier1_x = 43.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.frontier1_x = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier1_x", "double", 0, "coordinate-x of frontier i", "", &multi_exploration_simulatorConfig::frontier1_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier1_x", "double", 0, "coordinate-x of frontier i", "", &multi_exploration_simulatorConfig::frontier1_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.frontier1_y = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.frontier1_y = 13.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.frontier1_y = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier1_y", "double", 0, "coordinate-y of frontier i", "", &multi_exploration_simulatorConfig::frontier1_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier1_y", "double", 0, "coordinate-y of frontier i", "", &multi_exploration_simulatorConfig::frontier1_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.frontier2_x = -3.7;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.frontier2_x = 43.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.frontier2_x = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier2_x", "double", 0, "coordinate-x of frontier i", "", &multi_exploration_simulatorConfig::frontier2_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier2_x", "double", 0, "coordinate-x of frontier i", "", &multi_exploration_simulatorConfig::frontier2_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.frontier2_y = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.frontier2_y = 13.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.frontier2_y = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier2_y", "double", 0, "coordinate-y of frontier i", "", &multi_exploration_simulatorConfig::frontier2_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier2_y", "double", 0, "coordinate-y of frontier i", "", &multi_exploration_simulatorConfig::frontier2_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.frontier3_x = -3.7;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.frontier3_x = 43.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.frontier3_x = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier3_x", "double", 0, "coordinate-x of frontier i", "", &multi_exploration_simulatorConfig::frontier3_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier3_x", "double", 0, "coordinate-x of frontier i", "", &multi_exploration_simulatorConfig::frontier3_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.frontier3_y = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.frontier3_y = 13.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.frontier3_y = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier3_y", "double", 0, "coordinate-y of frontier i", "", &multi_exploration_simulatorConfig::frontier3_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier3_y", "double", 0, "coordinate-y of frontier i", "", &multi_exploration_simulatorConfig::frontier3_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.frontier4_x = -3.7;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.frontier4_x = 43.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.frontier4_x = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier4_x", "double", 0, "coordinate-x of frontier i", "", &multi_exploration_simulatorConfig::frontier4_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier4_x", "double", 0, "coordinate-x of frontier i", "", &multi_exploration_simulatorConfig::frontier4_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.frontier4_y = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.frontier4_y = 13.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.frontier4_y = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier4_y", "double", 0, "coordinate-y of frontier i", "", &multi_exploration_simulatorConfig::frontier4_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier4_y", "double", 0, "coordinate-y of frontier i", "", &multi_exploration_simulatorConfig::frontier4_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.frontier5_x = -3.7;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.frontier5_x = 43.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.frontier5_x = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier5_x", "double", 0, "coordinate-x of frontier i", "", &multi_exploration_simulatorConfig::frontier5_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier5_x", "double", 0, "coordinate-x of frontier i", "", &multi_exploration_simulatorConfig::frontier5_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.frontier5_y = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.frontier5_y = 13.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.frontier5_y = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier5_y", "double", 0, "coordinate-y of frontier i", "", &multi_exploration_simulatorConfig::frontier5_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier5_y", "double", 0, "coordinate-y of frontier i", "", &multi_exploration_simulatorConfig::frontier5_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.frontier6_x = -3.7;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.frontier6_x = 43.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.frontier6_x = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier6_x", "double", 0, "coordinate-x of frontier i", "", &multi_exploration_simulatorConfig::frontier6_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier6_x", "double", 0, "coordinate-x of frontier i", "", &multi_exploration_simulatorConfig::frontier6_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.frontier6_y = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.frontier6_y = 13.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.frontier6_y = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier6_y", "double", 0, "coordinate-y of frontier i", "", &multi_exploration_simulatorConfig::frontier6_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier6_y", "double", 0, "coordinate-y of frontier i", "", &multi_exploration_simulatorConfig::frontier6_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.frontier7_x = -3.7;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.frontier7_x = 43.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.frontier7_x = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier7_x", "double", 0, "coordinate-x of frontier i", "", &multi_exploration_simulatorConfig::frontier7_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier7_x", "double", 0, "coordinate-x of frontier i", "", &multi_exploration_simulatorConfig::frontier7_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.frontier7_y = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.frontier7_y = 13.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.frontier7_y = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier7_y", "double", 0, "coordinate-y of frontier i", "", &multi_exploration_simulatorConfig::frontier7_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier7_y", "double", 0, "coordinate-y of frontier i", "", &multi_exploration_simulatorConfig::frontier7_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.frontier8_x = -3.7;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.frontier8_x = 43.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.frontier8_x = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier8_x", "double", 0, "coordinate-x of frontier i", "", &multi_exploration_simulatorConfig::frontier8_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier8_x", "double", 0, "coordinate-x of frontier i", "", &multi_exploration_simulatorConfig::frontier8_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.frontier8_y = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.frontier8_y = 13.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.frontier8_y = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier8_y", "double", 0, "coordinate-y of frontier i", "", &multi_exploration_simulatorConfig::frontier8_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier8_y", "double", 0, "coordinate-y of frontier i", "", &multi_exploration_simulatorConfig::frontier8_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.frontier9_x = -3.7;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.frontier9_x = 43.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.frontier9_x = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier9_x", "double", 0, "coordinate-x of frontier i", "", &multi_exploration_simulatorConfig::frontier9_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier9_x", "double", 0, "coordinate-x of frontier i", "", &multi_exploration_simulatorConfig::frontier9_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.frontier9_y = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.frontier9_y = 13.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.frontier9_y = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier9_y", "double", 0, "coordinate-y of frontier i", "", &multi_exploration_simulatorConfig::frontier9_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier9_y", "double", 0, "coordinate-y of frontier i", "", &multi_exploration_simulatorConfig::frontier9_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.frontier10_x = -3.7;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.frontier10_x = 43.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.frontier10_x = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier10_x", "double", 0, "coordinate-x of frontier i", "", &multi_exploration_simulatorConfig::frontier10_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier10_x", "double", 0, "coordinate-x of frontier i", "", &multi_exploration_simulatorConfig::frontier10_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.frontier10_y = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.frontier10_y = 13.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.frontier10_y = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier10_y", "double", 0, "coordinate-y of frontier i", "", &multi_exploration_simulatorConfig::frontier10_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr(new multi_exploration_simulatorConfig::ParamDescription<double>("frontier10_y", "double", 0, "coordinate-y of frontier i", "", &multi_exploration_simulatorConfig::frontier10_y)));
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(multi_exploration_simulatorConfig::AbstractGroupDescriptionConstPtr(new multi_exploration_simulatorConfig::GroupDescription<multi_exploration_simulatorConfig::DEFAULT, multi_exploration_simulatorConfig>(Default)));
//#line 366 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<multi_exploration_simulatorConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<multi_exploration_simulatorConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    multi_exploration_simulatorConfig __max__;
    multi_exploration_simulatorConfig __min__;
    multi_exploration_simulatorConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const multi_exploration_simulatorConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static multi_exploration_simulatorConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &multi_exploration_simulatorConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const multi_exploration_simulatorConfig &multi_exploration_simulatorConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const multi_exploration_simulatorConfig &multi_exploration_simulatorConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const multi_exploration_simulatorConfig &multi_exploration_simulatorConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<multi_exploration_simulatorConfig::AbstractParamDescriptionConstPtr> &multi_exploration_simulatorConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<multi_exploration_simulatorConfig::AbstractGroupDescriptionConstPtr> &multi_exploration_simulatorConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const multi_exploration_simulatorConfigStatics *multi_exploration_simulatorConfig::__get_statics__()
  {
    const static multi_exploration_simulatorConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = multi_exploration_simulatorConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __MULTI_EXPLORATION_SIMULATORRECONFIGURATOR_H__
