//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the exploration package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __exploration__SEAMLESS_HYBRID_EXPLORATION_PARAMETER_RECONFIGURECONFIG_H__
#define __exploration__SEAMLESS_HYBRID_EXPLORATION_PARAMETER_RECONFIGURECONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace exploration
{
  class seamless_hybrid_exploration_parameter_reconfigureConfigStatics;

  class seamless_hybrid_exploration_parameter_reconfigureConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(seamless_hybrid_exploration_parameter_reconfigureConfig &config, const seamless_hybrid_exploration_parameter_reconfigureConfig &max, const seamless_hybrid_exploration_parameter_reconfigureConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const seamless_hybrid_exploration_parameter_reconfigureConfig &config1, const seamless_hybrid_exploration_parameter_reconfigureConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, seamless_hybrid_exploration_parameter_reconfigureConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const seamless_hybrid_exploration_parameter_reconfigureConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, seamless_hybrid_exploration_parameter_reconfigureConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const seamless_hybrid_exploration_parameter_reconfigureConfig &config) const = 0;
      virtual void getValue(const seamless_hybrid_exploration_parameter_reconfigureConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T seamless_hybrid_exploration_parameter_reconfigureConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (seamless_hybrid_exploration_parameter_reconfigureConfig::* field);

      virtual void clamp(seamless_hybrid_exploration_parameter_reconfigureConfig &config, const seamless_hybrid_exploration_parameter_reconfigureConfig &max, const seamless_hybrid_exploration_parameter_reconfigureConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const seamless_hybrid_exploration_parameter_reconfigureConfig &config1, const seamless_hybrid_exploration_parameter_reconfigureConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, seamless_hybrid_exploration_parameter_reconfigureConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const seamless_hybrid_exploration_parameter_reconfigureConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, seamless_hybrid_exploration_parameter_reconfigureConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const seamless_hybrid_exploration_parameter_reconfigureConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const seamless_hybrid_exploration_parameter_reconfigureConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, seamless_hybrid_exploration_parameter_reconfigureConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, seamless_hybrid_exploration_parameter_reconfigureConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<seamless_hybrid_exploration_parameter_reconfigureConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(seamless_hybrid_exploration_parameter_reconfigureConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("last_goal_effect"==(*_i)->name){last_goal_effect = boost::any_cast<bool>(val);}
        if("last_goal_tolerance"==(*_i)->name){last_goal_tolerance = boost::any_cast<double>(val);}
        if("canceled_goal_effect"==(*_i)->name){canceled_goal_effect = boost::any_cast<bool>(val);}
        if("canceled_goal_tolerance"==(*_i)->name){canceled_goal_tolerance = boost::any_cast<double>(val);}
        if("distance_weight"==(*_i)->name){distance_weight = boost::any_cast<double>(val);}
        if("direction_weight"==(*_i)->name){direction_weight = boost::any_cast<double>(val);}
        if("other_robot_weight"==(*_i)->name){other_robot_weight = boost::any_cast<double>(val);}
        if("duplicate_coeff"==(*_i)->name){duplicate_coeff = boost::any_cast<double>(val);}
        if("on_map_coeff"==(*_i)->name){on_map_coeff = boost::any_cast<double>(val);}
      }
    }

    bool last_goal_effect;
double last_goal_tolerance;
bool canceled_goal_effect;
double canceled_goal_tolerance;
double distance_weight;
double direction_weight;
double other_robot_weight;
double duplicate_coeff;
double on_map_coeff;

    bool state;
    std::string name;

    
}groups;



//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool last_goal_effect;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double last_goal_tolerance;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool canceled_goal_effect;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double canceled_goal_tolerance;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double distance_weight;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double direction_weight;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double other_robot_weight;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double duplicate_coeff;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double on_map_coeff;
//#line 228 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("seamless_hybrid_exploration_parameter_reconfigureConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const seamless_hybrid_exploration_parameter_reconfigureConfig &__max__ = __getMax__();
      const seamless_hybrid_exploration_parameter_reconfigureConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const seamless_hybrid_exploration_parameter_reconfigureConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const seamless_hybrid_exploration_parameter_reconfigureConfig &__getDefault__();
    static const seamless_hybrid_exploration_parameter_reconfigureConfig &__getMax__();
    static const seamless_hybrid_exploration_parameter_reconfigureConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const seamless_hybrid_exploration_parameter_reconfigureConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void seamless_hybrid_exploration_parameter_reconfigureConfig::ParamDescription<std::string>::clamp(seamless_hybrid_exploration_parameter_reconfigureConfig &config, const seamless_hybrid_exploration_parameter_reconfigureConfig &max, const seamless_hybrid_exploration_parameter_reconfigureConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class seamless_hybrid_exploration_parameter_reconfigureConfigStatics
  {
    friend class seamless_hybrid_exploration_parameter_reconfigureConfig;

    seamless_hybrid_exploration_parameter_reconfigureConfigStatics()
    {
seamless_hybrid_exploration_parameter_reconfigureConfig::GroupDescription<seamless_hybrid_exploration_parameter_reconfigureConfig::DEFAULT, seamless_hybrid_exploration_parameter_reconfigureConfig> Default("Default", "", 0, 0, true, &seamless_hybrid_exploration_parameter_reconfigureConfig::groups);
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.last_goal_effect = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.last_goal_effect = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.last_goal_effect = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(seamless_hybrid_exploration_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new seamless_hybrid_exploration_parameter_reconfigureConfig::ParamDescription<bool>("last_goal_effect", "bool", 0, "", "", &seamless_hybrid_exploration_parameter_reconfigureConfig::last_goal_effect)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(seamless_hybrid_exploration_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new seamless_hybrid_exploration_parameter_reconfigureConfig::ParamDescription<bool>("last_goal_effect", "bool", 0, "", "", &seamless_hybrid_exploration_parameter_reconfigureConfig::last_goal_effect)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.last_goal_tolerance = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.last_goal_tolerance = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.last_goal_tolerance = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(seamless_hybrid_exploration_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new seamless_hybrid_exploration_parameter_reconfigureConfig::ParamDescription<double>("last_goal_tolerance", "double", 0, "", "", &seamless_hybrid_exploration_parameter_reconfigureConfig::last_goal_tolerance)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(seamless_hybrid_exploration_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new seamless_hybrid_exploration_parameter_reconfigureConfig::ParamDescription<double>("last_goal_tolerance", "double", 0, "", "", &seamless_hybrid_exploration_parameter_reconfigureConfig::last_goal_tolerance)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.canceled_goal_effect = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.canceled_goal_effect = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.canceled_goal_effect = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(seamless_hybrid_exploration_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new seamless_hybrid_exploration_parameter_reconfigureConfig::ParamDescription<bool>("canceled_goal_effect", "bool", 0, "", "", &seamless_hybrid_exploration_parameter_reconfigureConfig::canceled_goal_effect)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(seamless_hybrid_exploration_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new seamless_hybrid_exploration_parameter_reconfigureConfig::ParamDescription<bool>("canceled_goal_effect", "bool", 0, "", "", &seamless_hybrid_exploration_parameter_reconfigureConfig::canceled_goal_effect)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.canceled_goal_tolerance = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.canceled_goal_tolerance = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.canceled_goal_tolerance = 0.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(seamless_hybrid_exploration_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new seamless_hybrid_exploration_parameter_reconfigureConfig::ParamDescription<double>("canceled_goal_tolerance", "double", 0, "", "", &seamless_hybrid_exploration_parameter_reconfigureConfig::canceled_goal_tolerance)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(seamless_hybrid_exploration_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new seamless_hybrid_exploration_parameter_reconfigureConfig::ParamDescription<double>("canceled_goal_tolerance", "double", 0, "", "", &seamless_hybrid_exploration_parameter_reconfigureConfig::canceled_goal_tolerance)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.distance_weight = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.distance_weight = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.distance_weight = 2.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(seamless_hybrid_exploration_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new seamless_hybrid_exploration_parameter_reconfigureConfig::ParamDescription<double>("distance_weight", "double", 0, "", "", &seamless_hybrid_exploration_parameter_reconfigureConfig::distance_weight)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(seamless_hybrid_exploration_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new seamless_hybrid_exploration_parameter_reconfigureConfig::ParamDescription<double>("distance_weight", "double", 0, "", "", &seamless_hybrid_exploration_parameter_reconfigureConfig::distance_weight)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.direction_weight = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.direction_weight = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.direction_weight = 1.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(seamless_hybrid_exploration_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new seamless_hybrid_exploration_parameter_reconfigureConfig::ParamDescription<double>("direction_weight", "double", 0, "", "", &seamless_hybrid_exploration_parameter_reconfigureConfig::direction_weight)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(seamless_hybrid_exploration_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new seamless_hybrid_exploration_parameter_reconfigureConfig::ParamDescription<double>("direction_weight", "double", 0, "", "", &seamless_hybrid_exploration_parameter_reconfigureConfig::direction_weight)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.other_robot_weight = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.other_robot_weight = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.other_robot_weight = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(seamless_hybrid_exploration_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new seamless_hybrid_exploration_parameter_reconfigureConfig::ParamDescription<double>("other_robot_weight", "double", 0, "", "", &seamless_hybrid_exploration_parameter_reconfigureConfig::other_robot_weight)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(seamless_hybrid_exploration_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new seamless_hybrid_exploration_parameter_reconfigureConfig::ParamDescription<double>("other_robot_weight", "double", 0, "", "", &seamless_hybrid_exploration_parameter_reconfigureConfig::other_robot_weight)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.duplicate_coeff = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.duplicate_coeff = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.duplicate_coeff = 1.2;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(seamless_hybrid_exploration_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new seamless_hybrid_exploration_parameter_reconfigureConfig::ParamDescription<double>("duplicate_coeff", "double", 0, "", "", &seamless_hybrid_exploration_parameter_reconfigureConfig::duplicate_coeff)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(seamless_hybrid_exploration_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new seamless_hybrid_exploration_parameter_reconfigureConfig::ParamDescription<double>("duplicate_coeff", "double", 0, "", "", &seamless_hybrid_exploration_parameter_reconfigureConfig::duplicate_coeff)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.on_map_coeff = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.on_map_coeff = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.on_map_coeff = 1.1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(seamless_hybrid_exploration_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new seamless_hybrid_exploration_parameter_reconfigureConfig::ParamDescription<double>("on_map_coeff", "double", 0, "", "", &seamless_hybrid_exploration_parameter_reconfigureConfig::on_map_coeff)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(seamless_hybrid_exploration_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr(new seamless_hybrid_exploration_parameter_reconfigureConfig::ParamDescription<double>("on_map_coeff", "double", 0, "", "", &seamless_hybrid_exploration_parameter_reconfigureConfig::on_map_coeff)));
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(seamless_hybrid_exploration_parameter_reconfigureConfig::AbstractGroupDescriptionConstPtr(new seamless_hybrid_exploration_parameter_reconfigureConfig::GroupDescription<seamless_hybrid_exploration_parameter_reconfigureConfig::DEFAULT, seamless_hybrid_exploration_parameter_reconfigureConfig>(Default)));
//#line 366 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<seamless_hybrid_exploration_parameter_reconfigureConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<seamless_hybrid_exploration_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<seamless_hybrid_exploration_parameter_reconfigureConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    seamless_hybrid_exploration_parameter_reconfigureConfig __max__;
    seamless_hybrid_exploration_parameter_reconfigureConfig __min__;
    seamless_hybrid_exploration_parameter_reconfigureConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const seamless_hybrid_exploration_parameter_reconfigureConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static seamless_hybrid_exploration_parameter_reconfigureConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &seamless_hybrid_exploration_parameter_reconfigureConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const seamless_hybrid_exploration_parameter_reconfigureConfig &seamless_hybrid_exploration_parameter_reconfigureConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const seamless_hybrid_exploration_parameter_reconfigureConfig &seamless_hybrid_exploration_parameter_reconfigureConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const seamless_hybrid_exploration_parameter_reconfigureConfig &seamless_hybrid_exploration_parameter_reconfigureConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<seamless_hybrid_exploration_parameter_reconfigureConfig::AbstractParamDescriptionConstPtr> &seamless_hybrid_exploration_parameter_reconfigureConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<seamless_hybrid_exploration_parameter_reconfigureConfig::AbstractGroupDescriptionConstPtr> &seamless_hybrid_exploration_parameter_reconfigureConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const seamless_hybrid_exploration_parameter_reconfigureConfigStatics *seamless_hybrid_exploration_parameter_reconfigureConfig::__get_statics__()
  {
    const static seamless_hybrid_exploration_parameter_reconfigureConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = seamless_hybrid_exploration_parameter_reconfigureConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __SEAMLESS_HYBRID_EXPLORATION_PARAMETER_RECONFIGURERECONFIGURATOR_H__
